apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapp
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
      - name: weatherapp
        image: ghcr.io/chandrubg/weatherapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
